site_name: OmegaT guides [cApStAn]
site_url: https://capstanlqc.github.com/omegat-guides
theme: 
  name: material
  features:
    - toc.follow
    - navigation.indexes 
markdown_extensions:
    - toc:
        baselevel: 1
        permalink: True
        separator: "_"
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - macros:
      verbose: true
      include_dir: docs/_includes
