site_name: OmegaT guides [cApStAn]
site_url: https://capstanlqc.github.com/omegat-guides
nav:
    - Contents: index.md
    - Tags: tags.md
    - Translation: 
        - Introduction: tasks/tra-intro.md
    - User Guides: 
        - Translation: tec-cb-ome-tra.md
        - Reconciliation: tec-cb-ome-rec.md
        - Adaptation: tec-cb-ome-adp.md
        - Proofreading: tec-cb-ome-prf.md
        - Verification: tec-cb-ome-ver.md
        - Verification CG: tec-cb-ome-ver-cg.md
    - Misc:
        - About: about.md
        - Installation and customization: tec-cb-ome-ins.md
        - Cheatsheet (shortcuts): cheatsheet.md
        - Bidirectionality: tec-omt-rtl.md
        - FAQ: tec-cb-ome-faq.md
    - Technical:
        - Security information: tec-cb-ome-sec.md
        - Markdown: markdown.md
theme:
  name: material
  features:
    #- toc.integrate
    - navigation.instant
    - navigation.prune
    #- navigation.sections    
    - navigation.tabs
    - toc.follow
    - navigation.indexes
markdown_extensions:
  - toc:
      baselevel: 2
      permalink: True
      separator: "_"
      toc_depth: 1-3
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde    
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg  
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - search
  - tags:
      tags_file: tags.md
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      tags_allowed:
        - Translation
        - Reconciliation
        - Verification
  - macros:
      verbose: true
      include_dir: docs/_includes
